[package]
name = "amnesia-client"
version = "0.1.0"
authors = ["realaravinth <realaravinth@batsense.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
actix-files = "0.2.1"
tokio = { version = "0.2", features = ["fs"] }
pnet = "0.26.0"

run_script = "0.6.3"
